import Head from "next/head";
import styles from "../styles/Home.module.css";
import UrlConnect from "../views/UrlConnect";
import BlogList from "../views/BlogList";
import ErrorBoundary from "../ErrorBoundary"; // error boundary component
import { w3cwebsocket as W3CWebSocket } from "websocket";

const SERVER_URL = "http://127.0.0.1:3001";
const WEBSOCKET_URL = "ws://127.0.0.1:3001";

const websocketClient = W3CWebSocket(WEBSOCKET_URL); // websocket client

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>check blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Blog List</h1>
        <ErrorBoundary>
          {/* input url and test connection */}
          <UrlConnect serverUrl={SERVER_URL} />
        </ErrorBoundary>
        <ErrorBoundary>
          {/* if connection opened, display posts */}
          <BlogList client={websocketClient} serverUrl={SERVER_URL} />
        </ErrorBoundary>
      </main>

      <footer className={styles.footer}>
        <h4>2022</h4>
      </footer>
    </div>
  );
}
